server:
  port: ${SERVER_PORT:8080}

spring:
  config:
    activate:
      on-profile: "dev"
  application:
    name: mohago-nocar
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:mohago_nocar}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      default_batch_fetch_size: 1000
      jdbc:
        time_zone: Asia/Seoul
    defer-datasource-initialization: true
    show-sql: true
    open-in-view: false

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
