server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: mohago-nocar
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:mohago_nocar}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      default_batch_fetch_size: 1000
      jdbc:
        time_zone: Asia/Seoul
    defer-datasource-initialization: true
    show-sql: true
    open-in-view: false

  data:
    redis:
      host: localhost
      port: 6379

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha

odsay:
  url: https://api.odsay.com/v1/api/searchPubTransPathT
  api-key: ${ODSAY_API_KEY}

google:
  maps:
    distance : https://maps.googleapis.com/maps/api/distancematrix/json
  api-key : ${GOOGLE_API_KEY}

kakao:
  local:
    category: https://dapi.kakao.com/v2/local/search/category
  api-key: ${KAKAO_API_KEY}
---
spring:
  config:
    activate:
      on-profile: dev
---
spring:
  config:
    activate:
      on-profile: test
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:~/mohagoNoCar
#    username: sa
#    password:
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
#        show_sql: true
#        format_sql: true
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
  data:
    redis:
      host: localhost
      port: 6378