name: Java CI with Gradle

on: 
  push:
    branches: [ "setting/#6" ]

jobs:
  deploy:

    runs-on: ubuntu-latest 
      
    steps: 
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
      
    # 환경 변수 파일 생성
    - name: Set environment values
      run: |
        cd ./src/main/resources # resources 폴더로 이동
        touch ./env.properties # env.properties 파일 생성
        echo "${{ secrets.ENV }}" > ./env.properties # github actions secret에서 가져온 값을 application.yml 파일에 씁니다
      shell: bash
    
    # Gradle 빌드 & 테스트
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Test with Gradle
      run: ./gradlew test

    - name: Run the Gradle package task
      run: ./gradlew build

    - name: Make zip file
      run: |
        mkdir deploy
        cp ./build/libs/*.jar ./deploy/
        zip -r -qq -j ./mohazi.zip ./deploy

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Upload to S3
      run: aws s3 cp --region ap-northeast-2 ./mohazi.zip s3://code-deploy-mohazi
