name: Require Code Owners Approval for Develop Branch

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  require-codeowners-approval:
    runs-on: ubuntu-latest
    steps:
      - name: Check approvals from Code Owners
        uses: actions/github-script@v6
        with:
          script: |
            const { data: reviews } = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });

            const approvedBy = new Set();
            reviews.forEach(review => {
              if (review.state === 'APPROVED') {
                approvedBy.add(review.user.login.toLowerCase());
              }
            });

            const codeOwners = ['mingmingmon', 'mungsil'];
            const prAuthor = context.payload.pull_request.user.login.toLowerCase();

            const isAuthorCodeOwner = codeOwners.includes(prAuthor);
            let requiredApprovals = [];
            if (isAuthorCodeOwner) {
              requiredApprovals = codeOwners.filter(user => user !== prAuthor);
            } else {
              requiredApprovals = codeOwners;
            }

            const allApproved = requiredApprovals.every(user => approvedBy.has(user));

            if (!allApproved) {
              throw new Error('모든 코드 소유자의 승인이 필요합니다.');
            }